apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mo-chat-aiops.fullname" . }}-config
  labels:
    {{- include "mo-chat-aiops.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  projects.yaml: |
{{ .Values.projectsConfig.content | indent 4 }}
